spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://119.23.74.131:3306/security?useUnicode=true&characterEncoding=utf-8&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 123456
  #session:
  #  store-type: redis

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  session:
    timeout: 3600
  port: 80

